<?php
if($this->lang == 'en') {?>
<h2>All Time Best Facts in the Italian Serie A</h2>
<p>Juventus has on the most Serie A titles, 36, and have also been crowned Italian champions in 9 consecutive seasons from 2011/2012 season to 2019/2020 season</p>
<p>Internazionale (Inter Milan) has featured the most times in the Italian Serie A, 89</p>
<p><a href='https://en.wikipedia.org/wiki/Gianluigi_Buffon' target='_blank' style='color:green; text-decoration: underline'>Gianluigi Buffon</a> has the most appearances in the Serie A, participating in 653 games from 1995 to 2006, 2007 to 2018 and 2019 till present and has played for Parma and Juventus only.</p>
<p><a href='https://en.wikipedia.org/wiki/Silvio_Piola' target='_blank' style='color:green; text-decoration: underline'>Silvio Piola</a> sccored the most Serie A goals and was active in the years 1929–1943, 1946–1947 and 1948–1954. He played for Pro Vercelli, Lazio, Juventus and Novara making a total of 537 Serie A appearances and scoring 274 times in the process ahead of Roma's legend, <a href='https://en.wikipedia.org/wiki/Francesco_Totti' target='_blank' style='color:green; text-decoration: underline'>Francesco Totti</a> who made all his 619 appearances and scored all his 250 Serie A goals for AS Roma, a true king.</p><?php
} elseif($this->lang == 'fr') {
    
} elseif($this->lang == 'es') {?>
<h2>Los mejores datos de todos los tiempos en la Serie A italiana</h2>
<p>La Juventus cuenta con la mayor cantidad de títulos de la Serie A, 36, y también se ha coronado campeona de Italia en 9 temporadas consecutivas desde la temporada 2011/2012 hasta la temporada 2019/2020</p>
<p>El Internazionale (Inter de Milán) ha sido el que más veces ha aparecido en la Serie A italiana, 89</p>
<p><a href='https://es.wikipedia.org/wiki/Gianluigi_Buffon' target='_blank' style='color:green; text-decoration: underline'>Gianluigi Buffon</a> tiene la mayor cantidad de apariciones en la Serie A, participando en 653 partidos de 1995 a 2006, 2007 a 2018 y 2019 hasta el presente y ha jugado solo para Parma y la Juventus.</p>
<p><a href='https://es.wikipedia.org/wiki/Silvio_Piola' target='_blank' style='color:green; text-decoration: underline'>Silvio Piola</a> smarcó más goles en la Serie A y estuvo activo en los años 1929–1943, 1946–1947 y 1948–1954. Jugó para Pro Vercelli, Lazio, Juventus y Novara haciendo un total de 537 apariciones de la Serie A y anotando 274 veces en el proceso por delante de la leyenda de Roma, <a href='https://es.wikipedia.org/wiki/Francesco_Totti' target='_blank' style='color:green; text-decoration: underline'>Francesco Totti</a> quien hizo todas sus 619 apariciones y anotó todos sus 250 goles de la Serie A para el AS Roma, un verdadero rey.</p><?php
} elseif($this->lang == 'pt') {?>
<h2>Melhores Fatos de Todos os Tempos da Série A Italiana</h2>
<p>A Juventus tem o maior número de títulos da Série A, somando 36, e também foi coroada campeã italiana em 9 temporadas consecutivas da temporada 2011/2012 até a temporada 2019/2020</p>
<p>A Internazionale (Inter de Milão) foi a que disputou mais vezes a Série A italiana, 89 ao todo</p>
<p><a href='https://pt.wikipedia.org/wiki/Gianluigi_Buffon' target='_blank' style='color:green; text-decoration: underline'>Gianluigi Buffon</a> tem o maior número de aparições na Série A, participando de 653 jogos de 1995 a 2006, 2007 a 2018 e 2019 até o presente, e jogou apenas pelo Parma e Juventus..</p>
<p><a href='https://pt.wikipedia.org/wiki/Silvio_Piola' target='_blank' style='color:green; text-decoration: underline'>Silvio Piola</a> marcou mais gols na Série A e atuou nos anos de 1929-1943, 1946-1947 e 1948-1954. Ele jogou para Pro Vercelli, Lazio, Juventus e Novara, totalizando 537 jogos na Serie A e marcando 274 vezes no processo, à frente da lenda da Roma, <a href='https://pt.wikipedia.org/wiki/Francesco_Totti' target='_blank' style='color:green; text-decoration: underline'>Francesco Totti</a> que fez um total de 619 aparições e 250 gols na Série A pela AS Roma, um verdadeiro rei.</p><?php
} elseif($this->lang == 'de') {?>
<h2>Die besten Fakten aller Zeiten in der italienischen Serie A</h2>
<p>Juventus ist der Verein mit den meisten Titeln in der Serie A (36) und wurde von der Saison 2011/2012 bis zur Saison 2019/2020 in 9 aufeinanderfolgenden Spielzeiten italienischer Meister</p>
<p>Internazionale (Inter Mailand) hat die meisten Spiele in der italienischen Serie A bestritten, 89</p>
<p><a href='https://de.wikipedia.org/wiki/Gianluigi_Buffon' target='_blank' style='color:green; text-decoration: underline'>Gianluigi Buffon</a> hat die meisten Einsätze in der Serie A, er hat von 1995 bis 2006, 2007 bis 2018 und 2019 bis heute 653 Spiele bestritten und hat nur für Parma und Juventus gespielt.</p>
<p><a href='https://de.wikipedia.org/wiki/Silvio_Piola' target='_blank' style='color:green; text-decoration: underline'>Silvio Piola</a> schoss die meisten Tore in der Serie A und war in den Jahren 1929-1943, 1946-1947 und 1948-1954 aktiv. Er spielte für Pro Vercelli, Lazio, Juventus und Novara und absolvierte insgesamt 537 Einsätze in der Serie A. Dabei erzielte er 274 Tore, noch vor der Roma-Legende, <a href='https://de.wikipedia.org/wiki/Francesco_Totti' target='_blank' style='color:green; text-decoration: underline'>Francesco Totti</a>, der alle seine 619 Einsätze und 250 Tore in der Serie A für den AS Roma absolvierte, ein wahrer König.</p><?php
} else {}