<p>La présente politique de confidentialité décrit la manière dont notre <a href="<?=HOME?>" style="color:green">site de prévisions footballistiques fiables</a> recueille, protège et utilise les informations personnelles que vous fournissez dessus, car la confidentialité de nos visiteurs est notre priorité absolue à côté du maitien de notre site comme <a href="<?=HOME?>" style="color:green">le meilleur site de prévisions de football au monde</a>. Il décrit également les choix qui s'offrent à vous concernant l'utilisation de vos informations personnelles et la manière dont vous pouvez accéder à ces informations et les mettre à jour. Cette politique ne s'applique pas aux pratiques des entreprises que nous ne possédons pas ou ne contrôlons pas, ni aux personnes que nous n'employons pas ou ne gérons pas.</p>

<h2>Fichiers journaux et collecte automatique d'informations</h2>
<p>BetaGamers suit une procédure standard d'utilisation des fichiers journaux. Lorsque vous visitez notre site, nos serveurs enregistrent automatiquement les informations envoyées  par votre navigateur. Ces données peuvent comprendre des informations telles que l'adresse IP de votre appareil, le type et la version de votre navigateur, le type et la version de votre système d'exploitation, vos préférences linguistiques, les pages de notre site que vous visitez, le temps passé sur ces pages, les informations que vous recherchez sur notre site, les heures et les dates d'accès et même la page web que vous visitiez avant de venir sur notre site, et ce principalement à des fins d'analyse et de statistiques.</p>

<p>Collecte, utilisation et traitement des informations personnelles</p>
<p>Pour utiliser certaines des fonctionnalités du site, il vous sera demandé de fournir certaines informations personnelles, qui peuvent principalement comprendre votre nom, votre adresse électronique, votre numéro de téléphone, votre adresse (pays) ou d'autres informations personnelles.</p> 
<p>Nous recevons et stockons toutes les informations que vous nous fournissez sciemment lorsque vous créez un compte, publiez un contenu ou un commentaire, ou remplissez un formulaire en ligne sur notre site.</p>
<p>Toutes les informations que nous recueillons auprès de vous peuvent être utilisées pour personnaliser votre expérience, améliorer notre site, améliorer le service clientèle et répondre aux questions et aux courriels de nos clients, envoyer des bulletins d'information, envoyer des courriels de notification tels que des rappels de mots de passe, des mises à jour, etc. Les informations collectées automatiquement ne sont utilisées que pour identifier des cas potentiels d'abus et établir des statistiques sur l'utilisation du site. Ces informations statistiques ne sont par ailleurs pas agrégées de manière à identifier un utilisateur particulier du système.</p>

<h2>Gestion des informations personnelles</h2>
<p>Une fois qu'un compte a été créé, vous pouvez consulter votre profil pour voir quelles informations sont disponibles. Vous avez le droit de modifier vos données personnelles, mais vous ne pouvez pas le faire directement sur le site. Vous devrez nous envoyer un courrier électronique avec les données à modifier afin que nous puissions les mettre à jour en conséquence.</p>

<h2>Politiques de protection de la vie privée des tiers</h2>
<p>La politique de confidentialité de BetaGamers ne s'applique pas aux autres annonceurs ou sites web. Nous vous conseillons donc de consulter les politiques de confidentialité respectives de ces serveurs publicitaires tiers pour obtenir des informations plus détaillées, car elles peuvent inclure leurs pratiques et des instructions sur la manière de refuser certaines options.</p>

<h2>Protection de la vie privée des enfants</h2>
<p>La protection des enfants et de leur vie privée lors de l'utilisation du site est une autre de nos priorités. Nous encourageons les parents et les tuteurs à observer, participer à et/ou surveiller et guider leurs activités en ligne.</p>
<p>BetaGamers ne recueille pas sciemment d'informations personnelles identifiables auprès d'enfants de moins de 13 ans. Si vous pensez que votre enfant a fourni ce type d'informations sur notre site, nous vous encourageons vivement à nous contacter immédiatement et nous ferons tout notre possible pour supprimer rapidement ces informations de nos dossiers.</p>

<h2>Sécurité de l'information</h2>
<p>Nous stockons les informations que vous fournissez sur des serveurs informatiques dans un environnement contrôlé et sécurisé, protégé contre tout accès, utilisation ou divulgation non autorisés. Nous maintenons des protections administratives, techniques et physiques raisonnables dans un effort de protection contre l'accès, l'utilisation, la modification et la divulgation non autorisés des informations personnelles sous son contrôle et sa garde. Cependant, aucune transmission de données sur Internet ou sur un réseau sans fil ne peut être garantie. Par conséquent, bien que nous nous efforcions de protéger vos informations personnelles, vous reconnaissez que (i) il existe des limites de sécurité et de confidentialité sur Internet qui sont hors de notre contrôle ; (ii) la sécurité, l'intégrité et la confidentialité de toutes les informations et données échangées entre vous et notre site Internet ne peuvent être garanties ; et (iii) ces informations et données peuvent être consultées ou altérées en cours de transit par un tiers, malgré tous les efforts déployés.</p>

<h2>Violation de données</h2>
<p>Dans le cas où nous nous rendrions compte que la sécurité du site a été compromise ou que les informations personnelles des utilisateurs ont été divulguées à des tiers non liés à la suite d'une activité externe, y compris, mais sans s'y limiter, des attaques de sécurité ou des fraudes, nous nous réservons le droit de prendre des mesures raisonnablement appropriées, y compris, mais sans s'y limiter, des enquêtes et des rapports, ainsi que la notification aux autorités chargées de l'application de la loi et la coopération avec celles-ci. En cas de violation de données, nous ferons des efforts raisonnables pour informer les personnes concernées si nous pensons qu'il existe un risque raisonnable de préjudice pour l'utilisateur à la suite de la violation ou si la notification est requise par la loi. Dans ce cas, nous publierons un avis sur le site et vous enverrons un courrier électronique.</p>

<h2>Modifications et mises à jour</h2>
<p>Nous pouvons mettre à jour cette politique de confidentialité de temps en temps à notre discrétion et nous vous informerons de toute modification de ce document en changeant la date de mise à jour en bas de cette page. Toute version mise à jour de la présente politique de confidentialité entrera en vigueur immédiatement après la publication de la politique de confidentialité révisée, sauf indication contraire. Votre utilisation continue du site ou des services après la date d'entrée en vigueur de la politique de confidentialité révisée (ou de tout autre acte spécifié à ce moment) constituera votre consentement à ces changements.</p>
<p>Toutefois, nous n'utiliserons pas, sans votre consentement, vos données personnelles d'une manière différente de celle qui a été indiquée au moment où vos données personnelles ont été collectées.</p>

<h2>Politique de confidentialité valable en ligne uniquement</h2>
<p>Cette politique de confidentialité s'applique uniquement à nos activités en ligne et est valable pour les visiteurs de notre site en ce qui concerne les informations qu'ils ont partagées et/ou collectées dans BetaGamers. Cette politique ne s’applique pas aux informations collectées hors ligne ou par des canaux autres que ce site.</p>

<h2>Consentement</h2>
<p>En utilisant notre site Web, vous acceptez par la présente notre politique de confidentialité et acceptez ses conditions générales.</p>

<p>Dernière mise à jour de ce document le 22 mai 2020</p>