<?php
// All countries
// length 252
$country_list = array(
    "AF" => array("name" => "Afghanistan", "phone" => 93),
    "AX" => array("name" => "Aland Islands", "phone" => 358),
    "AL" => array("name" => "Albanien", "phone" => 355),
    "DZ" => array("name" => "Algerien", "phone" => 213),
    "AS" => array("name" => "Amerikanischen Samoa-Inseln", "phone" => 1684),
    "AD" => array("name" => "Andorra", "phone" => 376),
    "AO" => array("name" => "Angola", "phone" => 244),
    "AI" => array("name" => "Anguilla", "phone" => 1264),
    "AQ" => array("name" => "Antarktis", "phone" => 672),
    "AG" => array("name" => "Antigua und Barbuda", "phone" => 1268),
    "AR" => array("name" => "Argentinien", "phone" => 54),
    "AM" => array("name" => "Armenien", "phone" => 374),
    "AW" => array("name" => "Aruba", "phone" => 297),
    "AU" => array("name" => "Australien", "phone" => 61),
    "AT" => array("name" => "Österreich", "phone" => 43),
    "AZ" => array("name" => "Aserbaidschan", "phone" => 994),
    "BS" => array("name" => "Bahamas", "phone" => 1242),
    "BH" => array("name" => "Bahrain", "phone" => 973),
    "BD" => array("name" => "Bangladesch", "phone" => 880),
    "BB" => array("name" => "Barbados", "phone" => 1246),
    "BY" => array("name" => "Weißrussland", "phone" => 375),
    "BE" => array("name" => "Belgien", "phone" => 32),
    "BZ" => array("name" => "Belize", "phone" => 501),
    "BJ" => array("name" => "Benin", "phone" => 229),
    "BM" => array("name" => "Bermuda", "phone" => 1441),
    "BT" => array("name" => "Bhutan", "phone" => 975),
    "BO" => array("name" => "Bolivien", "phone" => 591),
    "BQ" => array("name" => "Bonaire, Sint Eustatius und Saba", "phone" => 599),
    "BA" => array("name" => "Bosnien und Herzegowina", "phone" => 387),
    "BW" => array("name" => "Botswana", "phone" => 267),
    "BV" => array("name" => "Bouvet Island", "phone" => 55),
    "BR" => array("name" => "Brasilien", "phone" => 55),
    "IO" => array("name" => "Britisches Territorium des Indischen Ozeans", "phone" => 246),
    "BN" => array("name" => "Brunei Darussalam", "phone" => 673),
    "BG" => array("name" => "Bulgarien", "phone" => 359),
    "BF" => array("name" => "Burkina Faso", "phone" => 226),
    "BI" => array("name" => "Burundi", "phone" => 257),
    "KH" => array("name" => "Kambodscha", "phone" => 855),
    "CM" => array("name" => "Kamerun", "phone" => 237),
    "CA" => array("name" => "Kanada", "phone" => 1),
    "CV" => array("name" => "Kap Verde", "phone" => 238),
    "KY" => array("name" => "Cayman Inseln", "phone" => 1345),
    "CF" => array("name" => "Zentralafrikanische Republik", "phone" => 236),
    "TD" => array("name" => "Tschad", "phone" => 235),
    "CL" => array("name" => "Chile", "phone" => 56),
    "CN" => array("name" => "China", "phone" => 86),
    "CX" => array("name" => "Weihnachtsinsel", "phone" => 61),
    "CC" => array("name" => "Kokosinseln (Keelinginseln)", "phone" => 672),
    "CO" => array("name" => "Kolumbien", "phone" => 57),
    "KM" => array("name" => "Komoren", "phone" => 269),
    "CG" => array("name" => "Kongo", "phone" => 242),
    "CD" => array("name" => "Kongo, Demokratische Republik Kongo", "phone" => 242),
    "CK" => array("name" => "Cookinseln", "phone" => 682),
    "CR" => array("name" => "Costa Rica", "phone" => 506),
    "CI" => array("name" => "Elfenbeinküste", "phone" => 225),
    "HR" => array("name" => "Kroatien", "phone" => 385),
    "CU" => array("name" => "Kuba", "phone" => 53),
    "CW" => array("name" => "Curacao", "phone" => 599),
    "CY" => array("name" => "Zypern", "phone" => 357),
    "CZ" => array("name" => "Tschechien", "phone" => 420),
    "DK" => array("name" => "Dänemark", "phone" => 45),
    "DJ" => array("name" => "Dschibuti", "phone" => 253),
    "DM" => array("name" => "Dominica", "phone" => 1767),
    "DO" => array("name" => "Dominikanische Republik", "phone" => 1809),
    "EC" => array("name" => "Ecuador", "phone" => 593),
    "EG" => array("name" => "Ägypten", "phone" => 20),
    "SV" => array("name" => "El Salvador", "phone" => 503),
    "GQ" => array("name" => "Äquatorialguinea", "phone" => 240),
    "ER" => array("name" => "Eritrea", "phone" => 291),
    "EE" => array("name" => "Estland", "phone" => 372),
    "ET" => array("name" => "Äthiopien", "phone" => 251),
    "FK" => array("name" => "Falklandinseln (Malvinas)", "phone" => 500),
    "FO" => array("name" => "Färöer Inseln", "phone" => 298),
    "FJ" => array("name" => "Fidschi", "phone" => 679),
    "FI" => array("name" => "Finnland", "phone" => 358),
    "FR" => array("name" => "Frankreich", "phone" => 33),
    "GF" => array("name" => "Französisch-Guayana", "phone" => 594),
    "PF" => array("name" => "Französisch Polynesien", "phone" => 689),
    "TF" => array("name" => "Südfranzösische Territorien", "phone" => 262),
    "GA" => array("name" => "Gabun", "phone" => 241),
    "GM" => array("name" => "Gambia", "phone" => 220),
    "GE" => array("name" => "Georgia", "phone" => 995),
    "DE" => array("name" => "Deutschland", "phone" => 49),
    "GH" => array("name" => "Ghana", "phone" => 233),
    "GI" => array("name" => "Gibraltar", "phone" => 350),
    "GR" => array("name" => "Griechenland", "phone" => 30),
    "GL" => array("name" => "Grönland", "phone" => 299),
    "GD" => array("name" => "Grenada", "phone" => 1473),
    "GP" => array("name" => "Guadeloupe", "phone" => 590),
    "GU" => array("name" => "Guam", "phone" => 1671),
    "GT" => array("name" => "Guatemala", "phone" => 502),
    "GG" => array("name" => "Guernsey", "phone" => 44),
    "GN" => array("name" => "Guinea", "phone" => 224),
    "GW" => array("name" => "Guinea-Bissau", "phone" => 245),
    "GY" => array("name" => "Guyana", "phone" => 592),
    "HT" => array("name" => "Haiti", "phone" => 509),
    "HM" => array("name" => "Heard Island und McDonald Islands", "phone" => 0),
    "VA" => array("name" => "Heiliger Stuhl (Staat der Vatikanstadt)", "phone" => 39),
    "HN" => array("name" => "Honduras", "phone" => 504),
    "HK" => array("name" => "Hongkong", "phone" => 852),
    "HU" => array("name" => "Ungarn", "phone" => 36),
    "IS" => array("name" => "Island", "phone" => 354),
    "IN" => array("name" => "Indien", "phone" => 91),
    "ID" => array("name" => "Indonesien", "phone" => 62),
    "IR" => array("name" => "Iran, Islamische Republik", "phone" => 98),
    "IQ" => array("name" => "Irak", "phone" => 964),
    "IE" => array("name" => "Irland", "phone" => 353),
    "IM" => array("name" => "Isle of Man", "phone" => 44),
    "IL" => array("name" => "Israel", "phone" => 972),
    "IT" => array("name" => "Italien", "phone" => 39),
    "JM" => array("name" => "Jamaika", "phone" => 1876),
    "JP" => array("name" => "Japan", "phone" => 81),
    "JE" => array("name" => "Jersey", "phone" => 44),
    "JO" => array("name" => "Jordanien", "phone" => 962),
    "KZ" => array("name" => "Kasachstan", "phone" => 7),
    "KE" => array("name" => "Kenia", "phone" => 254),
    "KI" => array("name" => "Kiribati", "phone" => 686),
    "KP" => array("name" => "Korea, Demokratische Volksrepublik", "phone" => 850),
    "KR" => array("name" => "Korea, Republik von", "phone" => 82),
    "XK" => array("name" => "Kosovo", "phone" => 383),
    "KW" => array("name" => "Kuwait", "phone" => 965),
    "KG" => array("name" => "Kirgisistan", "phone" => 996),
    "LA" => array("name" => "Demokratische Volksrepublik Laos", "phone" => 856),
    "LV" => array("name" => "Lettland", "phone" => 371),
    "LB" => array("name" => "Libanon", "phone" => 961),
    "LS" => array("name" => "Lesotho", "phone" => 266),
    "LR" => array("name" => "Liberia", "phone" => 231),
    "LY" => array("name" => "Libyscher arabischer Jamahiriya", "phone" => 218),
    "LI" => array("name" => "Liechtenstein", "phone" => 423),
    "LT" => array("name" => "Litauen", "phone" => 370),
    "LU" => array("name" => "Luxemburg", "phone" => 352),
    "MO" => array("name" => "Macao", "phone" => 853),
    "MK" => array("name" => "Mazedonien, die ehemalige jugoslawische Republik", "phone" => 389),
    "MG" => array("name" => "Madagaskar", "phone" => 261),
    "MW" => array("name" => "Malawi", "phone" => 265),
    "MY" => array("name" => "Malaysia", "phone" => 60),
    "MV" => array("name" => "Malediven", "phone" => 960),
    "ML" => array("name" => "Mali", "phone" => 223),
    "MT" => array("name" => "Malta", "phone" => 356),
    "MH" => array("name" => "Marshallinseln", "phone" => 692),
    "MQ" => array("name" => "Martinique", "phone" => 596),
    "MR" => array("name" => "Mauretanien", "phone" => 222),
    "MU" => array("name" => "Mauritius", "phone" => 230),
    "YT" => array("name" => "Mayotte", "phone" => 262),
    "MX" => array("name" => "Mexiko", "phone" => 52),
    "FM" => array("name" => "Mikronesien, Föderierte Staaten von", "phone" => 691),
    "MD" => array("name" => "Moldawien, Republik", "phone" => 373),
    "MC" => array("name" => "Monaco", "phone" => 377),
    "MN" => array("name" => "Mongolei", "phone" => 976),
    "ME" => array("name" => "Montenegro", "phone" => 382),
    "MS" => array("name" => "Montserrat", "phone" => 1664),
    "MA" => array("name" => "Marokko", "phone" => 212),
    "MZ" => array("name" => "Mosambik", "phone" => 258),
    "MM" => array("name" => "Myanmar", "phone" => 95),
    "NA" => array("name" => "Namibia", "phone" => 264),
    "NR" => array("name" => "Nauru", "phone" => 674),
    "NP" => array("name" => "Nepal", "phone" => 977),
    "NL" => array("name" => "Niederlande", "phone" => 31),
    "AN" => array("name" => "Niederländische Antillen", "phone" => 599),
    "NC" => array("name" => "Neu-Kaledonien", "phone" => 687),
    "NZ" => array("name" => "Neuseeland", "phone" => 64),
    "NI" => array("name" => "Nicaragua", "phone" => 505),
    "NE" => array("name" => "Niger", "phone" => 227),
    "NG" => array("name" => "Nigeria", "phone" => 234),
    "NU" => array("name" => "Niue", "phone" => 683),
    "NF" => array("name" => "Norfolkinsel", "phone" => 672),
    "MP" => array("name" => "Nördliche Marianneninseln", "phone" => 1670),
    "NO" => array("name" => "Norwegen", "phone" => 47),
    "OM" => array("name" => "Oman", "phone" => 968),
    "PK" => array("name" => "Pakistan", "phone" => 92),
    "PW" => array("name" => "Palau", "phone" => 680),
    "PS" => array("name" => "Besetzte palästinensische Gebiete", "phone" => 970),
    "PA" => array("name" => "Panama", "phone" => 507),
    "PG" => array("name" => "Papua Neu-Guinea", "phone" => 675),
    "PY" => array("name" => "Paraguay", "phone" => 595),
    "PE" => array("name" => "Peru", "phone" => 51),
    "PH" => array("name" => "Philippinen", "phone" => 63),
    "PN" => array("name" => "Pitcairn", "phone" => 64),
    "PL" => array("name" => "Polen", "phone" => 48),
    "PT" => array("name" => "Portugal", "phone" => 351),
    "PR" => array("name" => "Puerto Rico", "phone" => 1787),
    "QA" => array("name" => "Katar", "phone" => 974),
    "RE" => array("name" => "Wiedervereinigung", "phone" => 262),
    "RO" => array("name" => "Rumänien", "phone" => 40),
    "RU" => array("name" => "Russische Föderation", "phone" => 7),
    "RW" => array("name" => "Ruanda", "phone" => 250),
    "BL" => array("name" => "Heiliger Barthelemy", "phone" => 590),
    "SH" => array("name" => "Heilige Helena", "phone" => 290),
    "KN" => array("name" => "St. Kitts und Nevis", "phone" => 1869),
    "LC" => array("name" => "St. Lucia", "phone" => 1758),
    "MF" => array("name" => "Sankt Martin", "phone" => 590),
    "PM" => array("name" => "Saint Pierre und Miquelon", "phone" => 508),
    "VC" => array("name" => "St. Vincent und die Grenadinen", "phone" => 1784),
    "WS" => array("name" => "Samoa", "phone" => 684),
    "SM" => array("name" => "San Marino", "phone" => 378),
    "ST" => array("name" => "Sao Tome und Principe", "phone" => 239),
    "SA" => array("name" => "Saudi-Arabien", "phone" => 966),
    "SN" => array("name" => "Senegal", "phone" => 221),
    "RS" => array("name" => "Serbien", "phone" => 381),
    "CS" => array("name" => "Serbien und Montenegro", "phone" => 381),
    "SC" => array("name" => "Seychellen", "phone" => 248),
    "SL" => array("name" => "Sierra Leone", "phone" => 232),
    "SG" => array("name" => "Singapur", "phone" => 65),
    "SX" => array("name" => "St. Martin", "phone" => 721),
    "SK" => array("name" => "Slowakei", "phone" => 421),
    "SI" => array("name" => "Slowenien", "phone" => 386),
    "SB" => array("name" => "Salomon-Inseln", "phone" => 677),
    "SO" => array("name" => "Somalia", "phone" => 252),
    "ZA" => array("name" => "Südafrika", "phone" => 27),
    "GS" => array("name" => "Süd-Georgien und die südlichen Sandwich-Inseln", "phone" => 500),
    "SS" => array("name" => "Südsudan", "phone" => 211),
    "ES" => array("name" => "Spanien", "phone" => 34),
    "LK" => array("name" => "Sri Lanka", "phone" => 94),
    "SD" => array("name" => "Sudan", "phone" => 249),
    "SR" => array("name" => "Suriname", "phone" => 597),
    "SJ" => array("name" => "Spitzbergen und Jan Mayen", "phone" => 47),
    "SZ" => array("name" => "Swasiland", "phone" => 268),
    "SE" => array("name" => "Schweden", "phone" => 46),
    "CH" => array("name" => "Schweiz", "phone" => 41),
    "SY" => array("name" => "Syrische Arabische Republik", "phone" => 963),
    "TW" => array("name" => "Taiwan, Provinz Chinas", "phone" => 886),
    "TJ" => array("name" => "Tadschikistan", "phone" => 992),
    "TZ" => array("name" => "Tansania, Vereinigte Republik", "phone" => 255),
    "TH" => array("name" => "Thailand", "phone" => 66),
    "TL" => array("name" => "Timor-Leste", "phone" => 670),
    "TG" => array("name" => "Togo", "phone" => 228),
    "TK" => array("name" => "Tokelau", "phone" => 690),
    "TO" => array("name" => "Tonga", "phone" => 676),
    "TT" => array("name" => "Trinidad und Tobago", "phone" => 1868),
    "TN" => array("name" => "Tunesien", "phone" => 216),
    "TR" => array("name" => "Türkei", "phone" => 90),
    "TM" => array("name" => "Turkmenistan", "phone" => 7370),
    "TC" => array("name" => "Turks- und Caicosinseln", "phone" => 1649),
    "TV" => array("name" => "Tuvalu", "phone" => 688),
    "UG" => array("name" => "Uganda", "phone" => 256),
    "UA" => array("name" => "Ukraine", "phone" => 380),
    "AE" => array("name" => "Vereinigte Arabische Emirate", "phone" => 971),
    "GB" => array("name" => "Vereinigtes Königreich", "phone" => 44),
    "US" => array("name" => "Vereinigte Staaten", "phone" => 1),
    "UM" => array("name" => "Kleinere abgelegene Inseln der Vereinigten Staaten", "phone" => 1),
    "UY" => array("name" => "Uruguay", "phone" => 598),
    "UZ" => array("name" => "Usbekistan", "phone" => 998),
    "VU" => array("name" => "Vanuatu", "phone" => 678),
    "VE" => array("name" => "Venezuela", "phone" => 58),
    "VN" => array("name" => "Vietnam", "phone" => 84),
    "VG" => array("name" => "Virgin Inseln, Britisch", "phone" => 1284),
    "VI" => array("name" => "Jungferninseln, USA", "phone" => 1340),
    "WF" => array("name" => "Wallis und Futuna", "phone" => 681),
    "EH" => array("name" => "Westsahara", "phone" => 212),
    "YE" => array("name" => "Jemen", "phone" => 967),
    "ZM" => array("name" => "Sambia", "phone" => 260),
    "ZW" => array("name" => "Zimbabwe", "phone" => 263)
);
?>