<?php
// All countries
// length 252
$country_list = array(
    "AF" => array("name" => "Afganistán", "phone" => 93),
    "AX" => array("name" => "Islas Aland", "phone" => 358),
    "AL" => array("name" => "Albania", "phone" => 355),
    "DZ" => array("name" => "Argelia", "phone" => 213),
    "AS" => array("name" => "Samoa Americana", "phone" => 1684),
    "AD" => array("name" => "Andorra", "phone" => 376),
    "AO" => array("name" => "Angola", "phone" => 244),
    "AI" => array("name" => "Anguila", "phone" => 1264),
    "AQ" => array("name" => "Antártida", "phone" => 672),
    "AG" => array("name" => "Antigua y Barbuda", "phone" => 1268),
    "AR" => array("name" => "Argentina", "phone" => 54),
    "AM" => array("name" => "Armenia", "phone" => 374),
    "AW" => array("name" => "Aruba", "phone" => 297),
    "AU" => array("name" => "Australia", "phone" => 61),
    "AT" => array("name" => "Austria", "phone" => 43),
    "AZ" => array("name" => "Azerbaiyán", "phone" => 994),
    "BS" => array("name" => "Bahamas", "phone" => 1242),
    "BH" => array("name" => "Bahréin", "phone" => 973),
    "BD" => array("name" => "Bangladesh", "phone" => 880),
    "BB" => array("name" => "Barbados", "phone" => 1246),
    "BY" => array("name" => "Bielorrusia", "phone" => 375),
    "BE" => array("name" => "Bélgica", "phone" => 32),
    "BZ" => array("name" => "Belice", "phone" => 501),
    "BJ" => array("name" => "Benin", "phone" => 229),
    "BM" => array("name" => "islas Bermudas", "phone" => 1441),
    "BT" => array("name" => "Bután", "phone" => 975),
    "BO" => array("name" => "Bolivia", "phone" => 591),
    "BQ" => array("name" => "Bonaire, Sint Eustatius y Saba", "phone" => 599),
    "BA" => array("name" => "Bosnia y Herzegovina", "phone" => 387),
    "BW" => array("name" => "Botswana", "phone" => 267),
    "BV" => array("name" => "Isla Bouvet", "phone" => 55),
    "BR" => array("name" => "Brasil", "phone" => 55),
    "IO" => array("name" => "Territorio Británico del Océano Índico", "phone" => 246),
    "BN" => array("name" => "Brunei Darussalam", "phone" => 673),
    "BG" => array("name" => "Bulgaria", "phone" => 359),
    "BF" => array("name" => "Burkina Faso", "phone" => 226),
    "BI" => array("name" => "Burundi", "phone" => 257),
    "KH" => array("name" => "Camboya", "phone" => 855),
    "CM" => array("name" => "Camerún", "phone" => 237),
    "CA" => array("name" => "Canadá", "phone" => 1),
    "CV" => array("name" => "Cabo Verde", "phone" => 238),
    "KY" => array("name" => "Islas Caimán", "phone" => 1345),
    "CF" => array("name" => "República Centroafricana", "phone" => 236),
    "TD" => array("name" => "Chad", "phone" => 235),
    "CL" => array("name" => "Chile", "phone" => 56),
    "CN" => array("name" => "porcelana", "phone" => 86),
    "CX" => array("name" => "Isla de Navidad", "phone" => 61),
    "CC" => array("name" => "Islas Cocos (Keeling)", "phone" => 672),
    "CO" => array("name" => "Colombia", "phone" => 57),
    "KM" => array("name" => "Comoras", "phone" => 269),
    "CG" => array("name" => "Congo", "phone" => 242),
    "CD" => array("name" => "Congo, República Democrática del Congo", "phone" => 242),
    "CK" => array("name" => "Islas Cook", "phone" => 682),
    "CR" => array("name" => "Costa Rica", "phone" => 506),
    "CI" => array("name" => "Costa de Marfil", "phone" => 225),
    "HR" => array("name" => "Croacia", "phone" => 385),
    "CU" => array("name" => "Cuba", "phone" => 53),
    "CW" => array("name" => "Curazao", "phone" => 599),
    "CY" => array("name" => "Chipre", "phone" => 357),
    "CZ" => array("name" => "Republica checa", "phone" => 420),
    "DK" => array("name" => "Dinamarca", "phone" => 45),
    "DJ" => array("name" => "Djibouti", "phone" => 253),
    "DM" => array("name" => "Dominica", "phone" => 1767),
    "DO" => array("name" => "República Dominicana", "phone" => 1809),
    "EC" => array("name" => "Ecuador", "phone" => 593),
    "EG" => array("name" => "Egipto", "phone" => 20),
    "SV" => array("name" => "El Salvador", "phone" => 503),
    "GQ" => array("name" => "Guinea Ecuatorial", "phone" => 240),
    "ER" => array("name" => "Eritrea", "phone" => 291),
    "EE" => array("name" => "Estonia", "phone" => 372),
    "ET" => array("name" => "Etiopía", "phone" => 251),
    "FK" => array("name" => "Islas Falkland (Malvinas)", "phone" => 500),
    "FO" => array("name" => "Islas Faroe", "phone" => 298),
    "FJ" => array("name" => "Fiyi", "phone" => 679),
    "FI" => array("name" => "Finlandia", "phone" => 358),
    "FR" => array("name" => "Francia", "phone" => 33),
    "GF" => array("name" => "Guayana Francesa", "phone" => 594),
    "PF" => array("name" => "Polinesia francés", "phone" => 689),
    "TF" => array("name" => "Territorios Franceses del Sur", "phone" => 262),
    "GA" => array("name" => "Gabón", "phone" => 241),
    "GM" => array("name" => "Gambia", "phone" => 220),
    "GE" => array("name" => "Georgia", "phone" => 995),
    "DE" => array("name" => "Alemania", "phone" => 49),
    "GH" => array("name" => "Ghana", "phone" => 233),
    "GI" => array("name" => "Gibraltar", "phone" => 350),
    "GR" => array("name" => "Grecia", "phone" => 30),
    "GL" => array("name" => "Groenlandia", "phone" => 299),
    "GD" => array("name" => "Granada", "phone" => 1473),
    "GP" => array("name" => "Guadalupe", "phone" => 590),
    "GU" => array("name" => "Guam", "phone" => 1671),
    "GT" => array("name" => "Guatemala", "phone" => 502),
    "GG" => array("name" => "Guernsey", "phone" => 44),
    "GN" => array("name" => "Guinea", "phone" => 224),
    "GW" => array("name" => "Guinea-Bissau", "phone" => 245),
    "GY" => array("name" => "Guayana", "phone" => 592),
    "HT" => array("name" => "Haití", "phone" => 509),
    "HM" => array("name" => "Islas Heard y McDonald", "phone" => 0),
    "VA" => array("name" => "Santa Sede (Estado de la Ciudad del Vaticano)", "phone" => 39),
    "HN" => array("name" => "Honduras", "phone" => 504),
    "HK" => array("name" => "Hong Kong", "phone" => 852),
    "HU" => array("name" => "Hungría", "phone" => 36),
    "IS" => array("name" => "Islandia", "phone" => 354),
    "IN" => array("name" => "India", "phone" => 91),
    "ID" => array("name" => "Indonesia", "phone" => 62),
    "IR" => array("name" => "Irán (República Islámica de", "phone" => 98),
    "IQ" => array("name" => "Irak", "phone" => 964),
    "IE" => array("name" => "Irlanda", "phone" => 353),
    "IM" => array("name" => "Isla del hombre", "phone" => 44),
    "IL" => array("name" => "Israel", "phone" => 972),
    "IT" => array("name" => "Italia", "phone" => 39),
    "JM" => array("name" => "Jamaica", "phone" => 1876),
    "JP" => array("name" => "Japón", "phone" => 81),
    "JE" => array("name" => "Jersey", "phone" => 44),
    "JO" => array("name" => "Jordán", "phone" => 962),
    "KZ" => array("name" => "Kazajstán", "phone" => 7),
    "KE" => array("name" => "Kenia", "phone" => 254),
    "KI" => array("name" => "Kiribati", "phone" => 686),
    "KP" => array("name" => "República de Corea, Popular Democrática de", "phone" => 850),
    "KR" => array("name" => "Corea, república de", "phone" => 82),
    "XK" => array("name" => "Kosovo", "phone" => 383),
    "KW" => array("name" => "Kuwait", "phone" => 965),
    "KG" => array("name" => "Kirguistán", "phone" => 996),
    "LA" => array("name" => "República Democrática Popular Lao", "phone" => 856),
    "LV" => array("name" => "Letonia", "phone" => 371),
    "LB" => array("name" => "Líbano", "phone" => 961),
    "LS" => array("name" => "Lesoto", "phone" => 266),
    "LR" => array("name" => "Liberia", "phone" => 231),
    "LY" => array("name" => "Jamahiriya Arabe Libia", "phone" => 218),
    "LI" => array("name" => "Liechtenstein", "phone" => 423),
    "LT" => array("name" => "Lituania", "phone" => 370),
    "LU" => array("name" => "Luxemburgo", "phone" => 352),
    "MO" => array("name" => "Macao", "phone" => 853),
    "MK" => array("name" => "Macedonia, la ex República Yugoslava de", "phone" => 389),
    "MG" => array("name" => "Madagascar", "phone" => 261),
    "MW" => array("name" => "Malawi", "phone" => 265),
    "MY" => array("name" => "Malasia", "phone" => 60),
    "MV" => array("name" => "Maldivas", "phone" => 960),
    "ML" => array("name" => "Mali", "phone" => 223),
    "MT" => array("name" => "Malta", "phone" => 356),
    "MH" => array("name" => "Islas Marshall", "phone" => 692),
    "MQ" => array("name" => "Martinica", "phone" => 596),
    "MR" => array("name" => "Mauritania", "phone" => 222),
    "MU" => array("name" => "Mauricio", "phone" => 230),
    "YT" => array("name" => "Mayotte", "phone" => 262),
    "MX" => array("name" => "México", "phone" => 52),
    "FM" => array("name" => "Micronesia, Estados Federados de", "phone" => 691),
    "MD" => array("name" => "Moldavia, República de", "phone" => 373),
    "MC" => array("name" => "Mónaco", "phone" => 377),
    "MN" => array("name" => "Mongolia", "phone" => 976),
    "ME" => array("name" => "Montenegro", "phone" => 382),
    "MS" => array("name" => "Montserrat", "phone" => 1664),
    "MA" => array("name" => "Marruecos", "phone" => 212),
    "MZ" => array("name" => "Mozambique", "phone" => 258),
    "MM" => array("name" => "Myanmar", "phone" => 95),
    "NA" => array("name" => "Namibia", "phone" => 264),
    "NR" => array("name" => "Nauru", "phone" => 674),
    "NP" => array("name" => "Nepal", "phone" => 977),
    "NL" => array("name" => "Países Bajos", "phone" => 31),
    "AN" => array("name" => "Antillas Holandesas", "phone" => 599),
    "NC" => array("name" => "Nueva Caledonia", "phone" => 687),
    "NZ" => array("name" => "Nueva Zelanda", "phone" => 64),
    "NI" => array("name" => "Nicaragua", "phone" => 505),
    "NE" => array("name" => "Níger", "phone" => 227),
    "NG" => array("name" => "Nigeria", "phone" => 234),
    "NU" => array("name" => "Niue", "phone" => 683),
    "NF" => array("name" => "Isla Norfolk", "phone" => 672),
    "MP" => array("name" => "Islas Marianas del Norte", "phone" => 1670),
    "NO" => array("name" => "Noruega", "phone" => 47),
    "OM" => array("name" => "Omán", "phone" => 968),
    "PK" => array("name" => "Pakistán", "phone" => 92),
    "PW" => array("name" => "Palau", "phone" => 680),
    "PS" => array("name" => "Territorio Palestino, Ocupado", "phone" => 970),
    "PA" => array("name" => "Panamá", "phone" => 507),
    "PG" => array("name" => "Papúa Nueva Guinea", "phone" => 675),
    "PY" => array("name" => "Paraguay", "phone" => 595),
    "PE" => array("name" => "Perú", "phone" => 51),
    "PH" => array("name" => "Filipinas", "phone" => 63),
    "PN" => array("name" => "Pitcairn", "phone" => 64),
    "PL" => array("name" => "Polonia", "phone" => 48),
    "PT" => array("name" => "Portugal", "phone" => 351),
    "PR" => array("name" => "Puerto Rico", "phone" => 1787),
    "QA" => array("name" => "Katar", "phone" => 974),
    "RE" => array("name" => "Reunión", "phone" => 262),
    "RO" => array("name" => "Rumania", "phone" => 40),
    "RU" => array("name" => "Federación Rusa", "phone" => 7),
    "RW" => array("name" => "Ruanda", "phone" => 250),
    "BL" => array("name" => "San Bartolomé", "phone" => 590),
    "SH" => array("name" => "Santa elena", "phone" => 290),
    "KN" => array("name" => "Saint Kitts y Nevis", "phone" => 1869),
    "LC" => array("name" => "Santa Lucía", "phone" => 1758),
    "MF" => array("name" => "San Martín", "phone" => 590),
    "PM" => array("name" => "San Pedro y Miquelón", "phone" => 508),
    "VC" => array("name" => "San Vicente y las Granadinas", "phone" => 1784),
    "WS" => array("name" => "Samoa", "phone" => 684),
    "SM" => array("name" => "San Marino", "phone" => 378),
    "ST" => array("name" => "Santo Tomé y Príncipe", "phone" => 239),
    "SA" => array("name" => "Arabia Saudita", "phone" => 966),
    "SN" => array("name" => "Senegal", "phone" => 221),
    "RS" => array("name" => "Serbia", "phone" => 381),
    "CS" => array("name" => "Serbia y Montenegro", "phone" => 381),
    "SC" => array("name" => "Seychelles", "phone" => 248),
    "SL" => array("name" => "Sierra Leona", "phone" => 232),
    "SG" => array("name" => "Singapur", "phone" => 65),
    "SX" => array("name" => "San Martín", "phone" => 721),
    "SK" => array("name" => "Eslovaquia", "phone" => 421),
    "SI" => array("name" => "Eslovenia", "phone" => 386),
    "SB" => array("name" => "Islas Salomón", "phone" => 677),
    "SO" => array("name" => "Somalia", "phone" => 252),
    "ZA" => array("name" => "Sudáfrica", "phone" => 27),
    "GS" => array("name" => "Georgia del sur y las islas Sandwich del sur", "phone" => 500),
    "SS" => array("name" => "Sudán del Sur", "phone" => 211),
    "ES" => array("name" => "España", "phone" => 34),
    "LK" => array("name" => "Sri Lanka", "phone" => 94),
    "SD" => array("name" => "Sudán", "phone" => 249),
    "SR" => array("name" => "Surinam", "phone" => 597),
    "SJ" => array("name" => "Svalbard y Jan Mayen", "phone" => 47),
    "SZ" => array("name" => "Swazilandia", "phone" => 268),
    "SE" => array("name" => "Suecia", "phone" => 46),
    "CH" => array("name" => "Suiza", "phone" => 41),
    "SY" => array("name" => "República Árabe Siria", "phone" => 963),
    "TW" => array("name" => "Taiwan, provincia de China", "phone" => 886),
    "TJ" => array("name" => "Tayikistán", "phone" => 992),
    "TZ" => array("name" => "Tanzania, República Unida de", "phone" => 255),
    "TH" => array("name" => "Tailandia", "phone" => 66),
    "TL" => array("name" => "Timor-Leste", "phone" => 670),
    "TG" => array("name" => "Togo", "phone" => 228),
    "TK" => array("name" => "Tokelau", "phone" => 690),
    "TO" => array("name" => "Tonga", "phone" => 676),
    "TT" => array("name" => "Trinidad y Tobago", "phone" => 1868),
    "TN" => array("name" => "Túnez", "phone" => 216),
    "TR" => array("name" => "Turquía", "phone" => 90),
    "TM" => array("name" => "Turkmenistán", "phone" => 7370),
    "TC" => array("name" => "Islas Turcas y Caicos", "phone" => 1649),
    "TV" => array("name" => "Tuvalu", "phone" => 688),
    "UG" => array("name" => "Uganda", "phone" => 256),
    "UA" => array("name" => "Ucrania", "phone" => 380),
    "AE" => array("name" => "Emiratos Árabes Unidos", "phone" => 971),
    "GB" => array("name" => "Reino Unido", "phone" => 44),
    "US" => array("name" => "Estados Unidos", "phone" => 1),
    "UM" => array("name" => "Islas menores alejadas de los Estados Unidos", "phone" => 1),
    "UY" => array("name" => "Uruguay", "phone" => 598),
    "UZ" => array("name" => "Uzbekistan", "phone" => 998),
    "VU" => array("name" => "Vanuatu", "phone" => 678),
    "VE" => array("name" => "Venezuela", "phone" => 58),
    "VN" => array("name" => "Vietnam", "phone" => 84),
    "VG" => array("name" => "Islas Vírgenes Británicas", "phone" => 1284),
    "VI" => array("name" => "Islas Vírgenes, EE. UU.", "phone" => 1340),
    "WF" => array("name" => "Wallis y Futuna", "phone" => 681),
    "EH" => array("name" => "Sahara Occidental", "phone" => 212),
    "YE" => array("name" => "Yemen", "phone" => 967),
    "ZM" => array("name" => "Zambia", "phone" => 260),
    "ZW" => array("name" => "Zimbabue", "phone" => 263)
);
?>