<?php
//setlocale(LC_ALL, 'fr');
// All countries
// length 252
$country_list = array(
    "AF" => array("name" => "L'Afghanistan", "phone" => 93),
    "AX" => array("name" => "Iles Aland", "phone" => 358),
    "AL" => array("name" => "Albanie", "phone" => 355),
    "DZ" => array("name" => "Algérie", "phone" => 213),
    "AS" => array("name" => "Samoa américaines", "phone" => 1684),
    "AD" => array("name" => "Andorre", "phone" => 376),
    "AO" => array("name" => "L'Angola", "phone" => 244),
    "AI" => array("name" => "Anguilla", "phone" => 1264),
    "AQ" => array("name" => "Antarctique", "phone" => 672),
    "AG" => array("name" => "Antigua-et-Barbuda", "phone" => 1268),
    "AR" => array("name" => "Argentine", "phone" => 54),
    "AM" => array("name" => "Arménie", "phone" => 374),
    "AW" => array("name" => "Aruba", "phone" => 297),
    "AU" => array("name" => "Australie", "phone" => 61),
    "AT" => array("name" => "L'Autriche", "phone" => 43),
    "AZ" => array("name" => "Azerbaïdjan", "phone" => 994),
    "BS" => array("name" => "Bahamas", "phone" => 1242),
    "BH" => array("name" => "Bahreïn", "phone" => 973),
    "BD" => array("name" => "Bangladesh", "phone" => 880),
    "BB" => array("name" => "Barbade", "phone" => 1246),
    "BY" => array("name" => "Biélorussie", "phone" => 375),
    "BE" => array("name" => "Belgique", "phone" => 32),
    "BZ" => array("name" => "Belize", "phone" => 501),
    "BJ" => array("name" => "Bénin", "phone" => 229),
    "BM" => array("name" => "Bermudes", "phone" => 1441),
    "BT" => array("name" => "Bhoutan", "phone" => 975),
    "BO" => array("name" => "Bolivie", "phone" => 591),
    "BQ" => array("name" => "Bonaire, Saint-Eustache et Saba", "phone" => 599),
    "BA" => array("name" => "Bosnie Herzégovine", "phone" => 387),
    "BW" => array("name" => "Botswana", "phone" => 267),
    "BV" => array("name" => "Île Bouvet", "phone" => 55),
    "BR" => array("name" => "Brésil", "phone" => 55),
    "IO" => array("name" => "Territoire britannique de l'océan Indien", "phone" => 246),
    "BN" => array("name" => "Brunei Darussalam", "phone" => 673),
    "BG" => array("name" => "Bulgarie", "phone" => 359),
    "BF" => array("name" => "Burkina Faso", "phone" => 226),
    "BI" => array("name" => "Burundi", "phone" => 257),
    "KH" => array("name" => "Cambodge", "phone" => 855),
    "CM" => array("name" => "Cameroun", "phone" => 237),
    "CA" => array("name" => "Canada", "phone" => 1),
    "CV" => array("name" => "Cap-Vert", "phone" => 238),
    "KY" => array("name" => "Îles Caïmans", "phone" => 1345),
    "CF" => array("name" => "République centrafricaine", "phone" => 236),
    "TD" => array("name" => "Tchad", "phone" => 235),
    "CL" => array("name" => "Chili", "phone" => 56),
    "CN" => array("name" => "Chine", "phone" => 86),
    "CX" => array("name" => "L'île de noël", "phone" => 61),
    "CC" => array("name" => "Îles Cocos (Keeling)", "phone" => 672),
    "CO" => array("name" => "Colombie", "phone" => 57),
    "KM" => array("name" => "Comores", "phone" => 269),
    "CG" => array("name" => "Congo", "phone" => 242),
    "CD" => array("name" => "Congo, République démocratique du Congo", "phone" => 242),
    "CK" => array("name" => "les Îles Cook", "phone" => 682),
    "CR" => array("name" => "Costa Rica", "phone" => 506),
    "CI" => array("name" => "Côte d'Ivoire", "phone" => 225),
    "HR" => array("name" => "Croatie", "phone" => 385),
    "CU" => array("name" => "Cuba", "phone" => 53),
    "CW" => array("name" => "Curacao", "phone" => 599),
    "CY" => array("name" => "Chypre", "phone" => 357),
    "CZ" => array("name" => "République Tchèque", "phone" => 420),
    "DK" => array("name" => "Danemark", "phone" => 45),
    "DJ" => array("name" => "Djibouti", "phone" => 253),
    "DM" => array("name" => "Dominique", "phone" => 1767),
    "DO" => array("name" => "République dominicaine", "phone" => 1809),
    "EC" => array("name" => "Equateur", "phone" => 593),
    "EG" => array("name" => "Egypte", "phone" => 20),
    "SV" => array("name" => "Le Salvador", "phone" => 503),
    "GQ" => array("name" => "Guinée Équatoriale", "phone" => 240),
    "ER" => array("name" => "Érythrée", "phone" => 291),
    "EE" => array("name" => "Estonie", "phone" => 372),
    "ET" => array("name" => "Ethiopie", "phone" => 251),
    "FK" => array("name" => "Îles Falkland (Malvinas)", "phone" => 500),
    "FO" => array("name" => "Îles Féroé", "phone" => 298),
    "FJ" => array("name" => "Fidji", "phone" => 679),
    "FI" => array("name" => "Finlande", "phone" => 358),
    "FR" => array("name" => "France", "phone" => 33),
    "GF" => array("name" => "Guyane Française", "phone" => 594),
    "PF" => array("name" => "Polynésie française", "phone" => 689),
    "TF" => array("name" => "Terres australes françaises", "phone" => 262),
    "GA" => array("name" => "Gabon", "phone" => 241),
    "GM" => array("name" => "Gambie", "phone" => 220),
    "GE" => array("name" => "Géorgie", "phone" => 995),
    "DE" => array("name" => "Allemagne", "phone" => 49),
    "GH" => array("name" => "Ghana", "phone" => 233),
    "GI" => array("name" => "Gibraltar", "phone" => 350),
    "GR" => array("name" => "Grèce", "phone" => 30),
    "GL" => array("name" => "Groenland", "phone" => 299),
    "GD" => array("name" => "Grenade", "phone" => 1473),
    "GP" => array("name" => "Guadeloupe", "phone" => 590),
    "GU" => array("name" => "Guam", "phone" => 1671),
    "GT" => array("name" => "Guatemala", "phone" => 502),
    "GG" => array("name" => "Guernesey", "phone" => 44),
    "GN" => array("name" => "Guinée", "phone" => 224),
    "GW" => array("name" => "Guinée-Bissau", "phone" => 245),
    "GY" => array("name" => "Guyane", "phone" => 592),
    "HT" => array("name" => "Haïti", "phone" => 509),
    "HM" => array("name" => "Îles Heard et McDonald", "phone" => 0),
    "VA" => array("name" => "Saint-Siège (État de la Cité du Vatican)", "phone" => 39),
    "HN" => array("name" => "Honduras", "phone" => 504),
    "HK" => array("name" => "Hong Kong", "phone" => 852),
    "HU" => array("name" => "Hongrie", "phone" => 36),
    "IS" => array("name" => "Islande", "phone" => 354),
    "IN" => array("name" => "Inde", "phone" => 91),
    "ID" => array("name" => "Indonésie", "phone" => 62),
    "IR" => array("name" => "Iran (République islamique d", "phone" => 98),
    "IQ" => array("name" => "Irak", "phone" => 964),
    "IE" => array("name" => "Irlande", "phone" => 353),
    "IM" => array("name" => "île de Man", "phone" => 44),
    "IL" => array("name" => "Israël", "phone" => 972),
    "IT" => array("name" => "Italie", "phone" => 39),
    "JM" => array("name" => "Jamaïque", "phone" => 1876),
    "JP" => array("name" => "Japon", "phone" => 81),
    "JE" => array("name" => "Jersey", "phone" => 44),
    "JO" => array("name" => "Jordan", "phone" => 962),
    "KZ" => array("name" => "Kazakhstan", "phone" => 7),
    "KE" => array("name" => "Kenya", "phone" => 254),
    "KI" => array("name" => "Kiribati", "phone" => 686),
    "KP" => array("name" => "République populaire démocratique de Corée", "phone" => 850),
    "KR" => array("name" => "Corée, République de", "phone" => 82),
    "XK" => array("name" => "Kosovo", "phone" => 383),
    "KW" => array("name" => "Koweit", "phone" => 965),
    "KG" => array("name" => "Kirghizistan", "phone" => 996),
    "LA" => array("name" => "République démocratique populaire lao", "phone" => 856),
    "LV" => array("name" => "Lettonie", "phone" => 371),
    "LB" => array("name" => "Liban", "phone" => 961),
    "LS" => array("name" => "Lesotho", "phone" => 266),
    "LR" => array("name" => "Libéria", "phone" => 231),
    "LY" => array("name" => "Jamahiriya arabe libyenne", "phone" => 218),
    "LI" => array("name" => "Liechtenstein", "phone" => 423),
    "LT" => array("name" => "Lituanie", "phone" => 370),
    "LU" => array("name" => "Luxembourg", "phone" => 352),
    "MO" => array("name" => "Macao", "phone" => 853),
    "MK" => array("name" => "Macédoine, ancienne République yougoslave de", "phone" => 389),
    "MG" => array("name" => "Madagascar", "phone" => 261),
    "MW" => array("name" => "Malawi", "phone" => 265),
    "MY" => array("name" => "Malaisie", "phone" => 60),
    "MV" => array("name" => "Maldives", "phone" => 960),
    "ML" => array("name" => "Mali", "phone" => 223),
    "MT" => array("name" => "Malte", "phone" => 356),
    "MH" => array("name" => "Iles Marshall", "phone" => 692),
    "MQ" => array("name" => "Martinique", "phone" => 596),
    "MR" => array("name" => "Mauritanie", "phone" => 222),
    "MU" => array("name" => "Ile Maurice", "phone" => 230),
    "YT" => array("name" => "Mayotte", "phone" => 262),
    "MX" => array("name" => "Mexique", "phone" => 52),
    "FM" => array("name" => "Micronésie, États fédérés de", "phone" => 691),
    "MD" => array("name" => "Moldova, République de", "phone" => 373),
    "MC" => array("name" => "Monaco", "phone" => 377),
    "MN" => array("name" => "Mongolie", "phone" => 976),
    "ME" => array("name" => "Monténégro", "phone" => 382),
    "MS" => array("name" => "Montserrat", "phone" => 1664),
    "MA" => array("name" => "Maroc", "phone" => 212),
    "MZ" => array("name" => "Mozambique", "phone" => 258),
    "MM" => array("name" => "Myanmar", "phone" => 95),
    "NA" => array("name" => "Namibie", "phone" => 264),
    "NR" => array("name" => "Nauru", "phone" => 674),
    "NP" => array("name" => "Népal", "phone" => 977),
    "NL" => array("name" => "Pays-Bas", "phone" => 31),
    "AN" => array("name" => "Antilles néerlandaises", "phone" => 599),
    "NC" => array("name" => "Nouvelle Calédonie", "phone" => 687),
    "NZ" => array("name" => "Nouvelle-Zélande", "phone" => 64),
    "NI" => array("name" => "Nicaragua", "phone" => 505),
    "NE" => array("name" => "Niger", "phone" => 227),
    "NG" => array("name" => "Nigeria", "phone" => 234),
    "NU" => array("name" => "Niue", "phone" => 683),
    "NF" => array("name" => "l'ile de Norfolk", "phone" => 672),
    "MP" => array("name" => "Îles Mariannes du Nord", "phone" => 1670),
    "NO" => array("name" => "Norvège", "phone" => 47),
    "OM" => array("name" => "Oman", "phone" => 968),
    "PK" => array("name" => "Pakistan", "phone" => 92),
    "PW" => array("name" => "Palau", "phone" => 680),
    "PS" => array("name" => "Territoire palestinien, occupé", "phone" => 970),
    "PA" => array("name" => "Panama", "phone" => 507),
    "PG" => array("name" => "Papouasie Nouvelle Guinée", "phone" => 675),
    "PY" => array("name" => "Paraguay", "phone" => 595),
    "PE" => array("name" => "Pérou", "phone" => 51),
    "PH" => array("name" => "Philippines", "phone" => 63),
    "PN" => array("name" => "Pitcairn", "phone" => 64),
    "PL" => array("name" => "Pologne", "phone" => 48),
    "PT" => array("name" => "Le Portugal", "phone" => 351),
    "PR" => array("name" => "Porto Rico", "phone" => 1787),
    "QA" => array("name" => "Qatar", "phone" => 974),
    "RE" => array("name" => "Réunion", "phone" => 262),
    "RO" => array("name" => "Roumanie", "phone" => 40),
    "RU" => array("name" => "Fédération Russe", "phone" => 7),
    "RW" => array("name" => "Rwanda", "phone" => 250),
    "BL" => array("name" => "Saint Barthélemy", "phone" => 590),
    "SH" => array("name" => "Sainte-Hélène", "phone" => 290),
    "KN" => array("name" => "Saint-Christophe-et-Niévès", "phone" => 1869),
    "LC" => array("name" => "Sainte-Lucie", "phone" => 1758),
    "MF" => array("name" => "Saint Martin", "phone" => 590),
    "PM" => array("name" => "Saint-Pierre-et-Miquelon", "phone" => 508),
    "VC" => array("name" => "Saint-Vincent-et-les-Grenadines", "phone" => 1784),
    "WS" => array("name" => "Samoa", "phone" => 684),
    "SM" => array("name" => "Saint Marin", "phone" => 378),
    "ST" => array("name" => "Sao Tomé et Principe", "phone" => 239),
    "SA" => array("name" => "Arabie Saoudite", "phone" => 966),
    "SN" => array("name" => "Sénégal", "phone" => 221),
    "RS" => array("name" => "Serbie", "phone" => 381),
    "CS" => array("name" => "Serbie et Monténégro", "phone" => 381),
    "SC" => array("name" => "les Seychelles", "phone" => 248),
    "SL" => array("name" => "Sierra Leone", "phone" => 232),
    "SG" => array("name" => "Singapour", "phone" => 65),
    "SX" => array("name" => "St Martin", "phone" => 721),
    "SK" => array("name" => "Slovaquie", "phone" => 421),
    "SI" => array("name" => "Slovénie", "phone" => 386),
    "SB" => array("name" => "Les îles Salomon", "phone" => 677),
    "SO" => array("name" => "Somalie", "phone" => 252),
    "ZA" => array("name" => "Afrique du Sud", "phone" => 27),
    "GS" => array("name" => "Géorgie du Sud et îles Sandwich du Sud", "phone" => 500),
    "SS" => array("name" => "Soudan du sud", "phone" => 211),
    "ES" => array("name" => "Espagne", "phone" => 34),
    "LK" => array("name" => "Sri Lanka", "phone" => 94),
    "SD" => array("name" => "Soudan", "phone" => 249),
    "SR" => array("name" => "Suriname", "phone" => 597),
    "SJ" => array("name" => "Svalbard et Jan Mayen", "phone" => 47),
    "SZ" => array("name" => "Swaziland", "phone" => 268),
    "SE" => array("name" => "Suède", "phone" => 46),
    "CH" => array("name" => "la Suisse", "phone" => 41),
    "SY" => array("name" => "République arabe syrienne", "phone" => 963),
    "TW" => array("name" => "Taiwan, Province de Chine", "phone" => 886),
    "TJ" => array("name" => "Tadjikistan", "phone" => 992),
    "TZ" => array("name" => "Tanzanie, République-Unie de", "phone" => 255),
    "TH" => array("name" => "Thaïlande", "phone" => 66),
    "TL" => array("name" => "Timor-Leste", "phone" => 670),
    "TG" => array("name" => "Togo", "phone" => 228),
    "TK" => array("name" => "Tokelau", "phone" => 690),
    "TO" => array("name" => "Tonga", "phone" => 676),
    "TT" => array("name" => "Trinité-et-Tobago", "phone" => 1868),
    "TN" => array("name" => "Tunisie", "phone" => 216),
    "TR" => array("name" => "Turquie", "phone" => 90),
    "TM" => array("name" => "Turkménistan", "phone" => 7370),
    "TC" => array("name" => "îles Turques-et-Caïques", "phone" => 1649),
    "TV" => array("name" => "Tuvalu", "phone" => 688),
    "UG" => array("name" => "Ouganda", "phone" => 256),
    "UA" => array("name" => "Ukraine", "phone" => 380),
    "AE" => array("name" => "Emirats Arabes Unis", "phone" => 971),
    "GB" => array("name" => "Royaume-Uni", "phone" => 44),
    "US" => array("name" => "États-Unis", "phone" => 1),
    "UM" => array("name" => "Îles mineures éloignées des États-Unis", "phone" => 1),
    "UY" => array("name" => "Uruguay", "phone" => 598),
    "UZ" => array("name" => "Ouzbékistan", "phone" => 998),
    "VU" => array("name" => "Vanuatu", "phone" => 678),
    "VE" => array("name" => "Venezuela", "phone" => 58),
    "VN" => array("name" => "Viet Nam", "phone" => 84),
    "VG" => array("name" => "Îles Vierges britanniques", "phone" => 1284),
    "VI" => array("name" => "Îles Vierges américaines, États-Unis", "phone" => 1340),
    "WF" => array("name" => "Wallis et Futuna", "phone" => 681),
    "EH" => array("name" => "Sahara occidental", "phone" => 212),
    "YE" => array("name" => "Yémen", "phone" => 967),
    "ZM" => array("name" => "Zambie", "phone" => 260),
    "ZW" => array("name" => "Zimbabwe", "phone" => 263)
);
//$arr = array_column($country_list, 'name');
//collator_asort( $coll, $arr);
/*
$flat = array();
foreach ($country_list as $index => $item) {
    $flat[$index] = $item['name'];
}
setlocale(LC_COLLATE, 'fr');
asort($flat, SORT_LOCALE_STRING);
*/
function cmp($a, $b) {
    // return strcasecmp($a['name'], $b['name']);
    $coll = collator_create( 'fr' );
    return collator_compare( $coll, $a['name'], $b['name'] );
}
//$coll = collator_create( 'en_US' );
//$res  = collator_compare( $coll, $s1, $s2 );
uasort($country_list, 'cmp');
//array_multisort(array_column($country_list, 'name'), SORT_ASC, SORT_LOCALE_STRING, $country_list);
//show($country_list);
?>