<?php
// All countries
// length 252
$country_list = array(
    "AF" => array("name" => "Afeganistão", "phone" => 93),
    "AX" => array("name" => "Ilhas Aland", "phone" => 358),
    "AL" => array("name" => "Albânia", "phone" => 355),
    "DZ" => array("name" => "Argélia", "phone" => 213),
    "AS" => array("name" => "Samoa Americana", "phone" => 1684),
    "AD" => array("name" => "Andorra", "phone" => 376),
    "AO" => array("name" => "Angola", "phone" => 244),
    "AI" => array("name" => "Anguilla", "phone" => 1264),
    "AQ" => array("name" => "Antártica", "phone" => 672),
    "AG" => array("name" => "Antigua e Barbuda", "phone" => 1268),
    "AR" => array("name" => "Argentina", "phone" => 54),
    "AM" => array("name" => "Armênia", "phone" => 374),
    "AW" => array("name" => "Aruba", "phone" => 297),
    "AU" => array("name" => "Austrália", "phone" => 61),
    "AT" => array("name" => "Áustria", "phone" => 43),
    "AZ" => array("name" => "Azerbaijão", "phone" => 994),
    "BS" => array("name" => "Bahamas", "phone" => 1242),
    "BH" => array("name" => "Bahrain", "phone" => 973),
    "BD" => array("name" => "Bangladesh", "phone" => 880),
    "BB" => array("name" => "Barbados", "phone" => 1246),
    "BY" => array("name" => "Bielo-Rússia", "phone" => 375),
    "BE" => array("name" => "Bélgica", "phone" => 32),
    "BZ" => array("name" => "Belize", "phone" => 501),
    "BJ" => array("name" => "Benin", "phone" => 229),
    "BM" => array("name" => "Bermudas", "phone" => 1441),
    "BT" => array("name" => "Butão", "phone" => 975),
    "BO" => array("name" => "Bolívia", "phone" => 591),
    "BQ" => array("name" => "Bonaire, Sint Eustatius e Saba", "phone" => 599),
    "BA" => array("name" => "Bósnia e Herzegovina", "phone" => 387),
    "BW" => array("name" => "Botswana", "phone" => 267),
    "BV" => array("name" => "Ilha Bouvet", "phone" => 55),
    "BR" => array("name" => "Brasil", "phone" => 55),
    "IO" => array("name" => "Território Britânico do Oceano Índico", "phone" => 246),
    "BN" => array("name" => "Brunei Darussalam", "phone" => 673),
    "BG" => array("name" => "Bulgária", "phone" => 359),
    "BF" => array("name" => "Burkina Faso", "phone" => 226),
    "BI" => array("name" => "Burundi", "phone" => 257),
    "KH" => array("name" => "Camboja", "phone" => 855),
    "CM" => array("name" => "Camarões", "phone" => 237),
    "CA" => array("name" => "Canadá", "phone" => 1),
    "CV" => array("name" => "cabo Verde", "phone" => 238),
    "KY" => array("name" => "Ilhas Cayman", "phone" => 1345),
    "CF" => array("name" => "República Centro-Africana", "phone" => 236),
    "TD" => array("name" => "Chade", "phone" => 235),
    "CL" => array("name" => "Chile", "phone" => 56),
    "CN" => array("name" => "China", "phone" => 86),
    "CX" => array("name" => "Ilha do Natal", "phone" => 61),
    "CC" => array("name" => "Ilhas Cocos (Keeling)", "phone" => 672),
    "CO" => array("name" => "Colômbia", "phone" => 57),
    "KM" => array("name" => "Comores", "phone" => 269),
    "CG" => array("name" => "Congo", "phone" => 242),
    "CD" => array("name" => "Congo, República Democrática do Congo", "phone" => 242),
    "CK" => array("name" => "Ilhas Cook", "phone" => 682),
    "CR" => array("name" => "Costa Rica", "phone" => 506),
    "CI" => array("name" => "Cote D'Ivoire", "phone" => 225),
    "HR" => array("name" => "Croácia", "phone" => 385),
    "CU" => array("name" => "Cuba", "phone" => 53),
    "CW" => array("name" => "Curaçao", "phone" => 599),
    "CY" => array("name" => "Chipre", "phone" => 357),
    "CZ" => array("name" => "República Checa", "phone" => 420),
    "DK" => array("name" => "Dinamarca", "phone" => 45),
    "DJ" => array("name" => "Djibouti", "phone" => 253),
    "DM" => array("name" => "Dominica", "phone" => 1767),
    "DO" => array("name" => "República Dominicana", "phone" => 1809),
    "EC" => array("name" => "Equador", "phone" => 593),
    "EG" => array("name" => "Egito", "phone" => 20),
    "SV" => array("name" => "El Salvador", "phone" => 503),
    "GQ" => array("name" => "Guiné Equatorial", "phone" => 240),
    "ER" => array("name" => "Eritreia", "phone" => 291),
    "EE" => array("name" => "Estônia", "phone" => 372),
    "ET" => array("name" => "Etiópia", "phone" => 251),
    "FK" => array("name" => "Ilhas Falkland (Malvinas)", "phone" => 500),
    "FO" => array("name" => "ilhas Faroe", "phone" => 298),
    "FJ" => array("name" => "Fiji", "phone" => 679),
    "FI" => array("name" => "Finlândia", "phone" => 358),
    "FR" => array("name" => "França", "phone" => 33),
    "GF" => array("name" => "Guiana Francesa", "phone" => 594),
    "PF" => array("name" => "Polinésia Francesa", "phone" => 689),
    "TF" => array("name" => "Territórios Franceses do Sul", "phone" => 262),
    "GA" => array("name" => "Gabão", "phone" => 241),
    "GM" => array("name" => "Gâmbia", "phone" => 220),
    "GE" => array("name" => "Georgia", "phone" => 995),
    "DE" => array("name" => "Alemanha", "phone" => 49),
    "GH" => array("name" => "Gana", "phone" => 233),
    "GI" => array("name" => "Gibraltar", "phone" => 350),
    "GR" => array("name" => "Grécia", "phone" => 30),
    "GL" => array("name" => "Groenlândia", "phone" => 299),
    "GD" => array("name" => "Grenada", "phone" => 1473),
    "GP" => array("name" => "Guadalupe", "phone" => 590),
    "GU" => array("name" => "Guam", "phone" => 1671),
    "GT" => array("name" => "Guatemala", "phone" => 502),
    "GG" => array("name" => "Guernsey", "phone" => 44),
    "GN" => array("name" => "Guiné", "phone" => 224),
    "GW" => array("name" => "Guinea-bissau", "phone" => 245),
    "GY" => array("name" => "Guiana", "phone" => 592),
    "HT" => array("name" => "Haiti", "phone" => 509),
    "HM" => array("name" => "Ilha Heard e Ilhas McDonald", "phone" => 0),
    "VA" => array("name" => "Santa Sé (Estado da Cidade do Vaticano)", "phone" => 39),
    "HN" => array("name" => "Honduras", "phone" => 504),
    "HK" => array("name" => "Hong Kong", "phone" => 852),
    "HU" => array("name" => "Hungria", "phone" => 36),
    "IS" => array("name" => "Islândia", "phone" => 354),
    "IN" => array("name" => "Índia", "phone" => 91),
    "ID" => array("name" => "Indonésia", "phone" => 62),
    "IR" => array("name" => "Irã (Republic Islâmica do Irã", "phone" => 98),
    "IQ" => array("name" => "Iraque", "phone" => 964),
    "IE" => array("name" => "Irlanda", "phone" => 353),
    "IM" => array("name" => "Ilha de Man", "phone" => 44),
    "IL" => array("name" => "Israel", "phone" => 972),
    "IT" => array("name" => "Itália", "phone" => 39),
    "JM" => array("name" => "Jamaica", "phone" => 1876),
    "JP" => array("name" => "Japão", "phone" => 81),
    "JE" => array("name" => "Jersey", "phone" => 44),
    "JO" => array("name" => "Jordânia", "phone" => 962),
    "KZ" => array("name" => "Cazaquistão", "phone" => 7),
    "KE" => array("name" => "Quênia", "phone" => 254),
    "KI" => array("name" => "Kiribati", "phone" => 686),
    "KP" => array("name" => "Coréia, República Popular Democrática da", "phone" => 850),
    "KR" => array("name" => "Republica da Coréia", "phone" => 82),
    "XK" => array("name" => "Kosovo", "phone" => 383),
    "KW" => array("name" => "Kuwait", "phone" => 965),
    "KG" => array("name" => "Quirguistão", "phone" => 996),
    "LA" => array("name" => "República Democrática Popular do Laos", "phone" => 856),
    "LV" => array("name" => "Letônia", "phone" => 371),
    "LB" => array("name" => "Líbano", "phone" => 961),
    "LS" => array("name" => "Lesoto", "phone" => 266),
    "LR" => array("name" => "Libéria", "phone" => 231),
    "LY" => array("name" => "Jamahiriya Árabe da Líbia", "phone" => 218),
    "LI" => array("name" => "Liechtenstein", "phone" => 423),
    "LT" => array("name" => "Lituânia", "phone" => 370),
    "LU" => array("name" => "Luxemburgo", "phone" => 352),
    "MO" => array("name" => "Macau", "phone" => 853),
    "MK" => array("name" => "Macedônia, Antiga República Iugoslava da", "phone" => 389),
    "MG" => array("name" => "Madagáscar", "phone" => 261),
    "MW" => array("name" => "Malawi", "phone" => 265),
    "MY" => array("name" => "Malásia", "phone" => 60),
    "MV" => array("name" => "Maldivas", "phone" => 960),
    "ML" => array("name" => "Mali", "phone" => 223),
    "MT" => array("name" => "Malta", "phone" => 356),
    "MH" => array("name" => "Ilhas Marshall", "phone" => 692),
    "MQ" => array("name" => "Martinica", "phone" => 596),
    "MR" => array("name" => "Mauritânia", "phone" => 222),
    "MU" => array("name" => "Maurício", "phone" => 230),
    "YT" => array("name" => "Mayotte", "phone" => 262),
    "MX" => array("name" => "México", "phone" => 52),
    "FM" => array("name" => "Micronésia, Estados Federados da", "phone" => 691),
    "MD" => array("name" => "Moldávia, República da", "phone" => 373),
    "MC" => array("name" => "Mônaco", "phone" => 377),
    "MN" => array("name" => "Mongólia", "phone" => 976),
    "ME" => array("name" => "Montenegro", "phone" => 382),
    "MS" => array("name" => "Montserrat", "phone" => 1664),
    "MA" => array("name" => "Marrocos", "phone" => 212),
    "MZ" => array("name" => "Moçambique", "phone" => 258),
    "MM" => array("name" => "Myanmar", "phone" => 95),
    "NA" => array("name" => "Namibia", "phone" => 264),
    "NR" => array("name" => "Nauru", "phone" => 674),
    "NP" => array("name" => "Nepal", "phone" => 977),
    "NL" => array("name" => "Países Baixos", "phone" => 31),
    "AN" => array("name" => "Antilhas Holandesas", "phone" => 599),
    "NC" => array("name" => "Nova Caledônia", "phone" => 687),
    "NZ" => array("name" => "Nova Zelândia", "phone" => 64),
    "NI" => array("name" => "Nicarágua", "phone" => 505),
    "NE" => array("name" => "Níger", "phone" => 227),
    "NG" => array("name" => "Nigéria", "phone" => 234),
    "NU" => array("name" => "Niue", "phone" => 683),
    "NF" => array("name" => "Ilha Norfolk", "phone" => 672),
    "MP" => array("name" => "Ilhas Marianas do Norte", "phone" => 1670),
    "NO" => array("name" => "Noruega", "phone" => 47),
    "OM" => array("name" => "Omã", "phone" => 968),
    "PK" => array("name" => "Paquistão", "phone" => 92),
    "PW" => array("name" => "Palau", "phone" => 680),
    "PS" => array("name" => "Território Palestino, Ocupado", "phone" => 970),
    "PA" => array("name" => "Panamá", "phone" => 507),
    "PG" => array("name" => "Papua Nova Guiné", "phone" => 675),
    "PY" => array("name" => "Paraguai", "phone" => 595),
    "PE" => array("name" => "Peru", "phone" => 51),
    "PH" => array("name" => "Filipinas", "phone" => 63),
    "PN" => array("name" => "Pitcairn", "phone" => 64),
    "PL" => array("name" => "Polônia", "phone" => 48),
    "PT" => array("name" => "Portugal", "phone" => 351),
    "PR" => array("name" => "Porto Rico", "phone" => 1787),
    "QA" => array("name" => "Catar", "phone" => 974),
    "RE" => array("name" => "Reunião", "phone" => 262),
    "RO" => array("name" => "Romênia", "phone" => 40),
    "RU" => array("name" => "Federação Russa", "phone" => 7),
    "RW" => array("name" => "Ruanda", "phone" => 250),
    "BL" => array("name" => "São Bartolomeu", "phone" => 590),
    "SH" => array("name" => "Santa Helena", "phone" => 290),
    "KN" => array("name" => "São Cristóvão e Neves", "phone" => 1869),
    "LC" => array("name" => "Santa Lúcia", "phone" => 1758),
    "MF" => array("name" => "são Martinho", "phone" => 590),
    "PM" => array("name" => "São Pedro e Miquelão", "phone" => 508),
    "VC" => array("name" => "São Vicente e Granadinas", "phone" => 1784),
    "WS" => array("name" => "Samoa", "phone" => 684),
    "SM" => array("name" => "San Marino", "phone" => 378),
    "ST" => array("name" => "São Tomé e Príncipe", "phone" => 239),
    "SA" => array("name" => "Arábia Saudita", "phone" => 966),
    "SN" => array("name" => "Senegal", "phone" => 221),
    "RS" => array("name" => "Sérvia", "phone" => 381),
    "CS" => array("name" => "Sérvia e Montenegro", "phone" => 381),
    "SC" => array("name" => "Seychelles", "phone" => 248),
    "SL" => array("name" => "Serra Leoa", "phone" => 232),
    "SG" => array("name" => "Cingapura", "phone" => 65),
    "SX" => array("name" => "St Martin", "phone" => 721),
    "SK" => array("name" => "Eslováquia", "phone" => 421),
    "SI" => array("name" => "Eslovênia", "phone" => 386),
    "SB" => array("name" => "Ilhas Salomão", "phone" => 677),
    "SO" => array("name" => "Somália", "phone" => 252),
    "ZA" => array("name" => "África do Sul", "phone" => 27),
    "GS" => array("name" => "Geórgia do Sul e Ilhas Sandwich do Sul", "phone" => 500),
    "SS" => array("name" => "Sudão do Sul", "phone" => 211),
    "ES" => array("name" => "Espanha", "phone" => 34),
    "LK" => array("name" => "Sri Lanka", "phone" => 94),
    "SD" => array("name" => "Sudão", "phone" => 249),
    "SR" => array("name" => "Suriname", "phone" => 597),
    "SJ" => array("name" => "Svalbard e Jan Mayen", "phone" => 47),
    "SZ" => array("name" => "Suazilândia", "phone" => 268),
    "SE" => array("name" => "Suécia", "phone" => 46),
    "CH" => array("name" => "Suíça", "phone" => 41),
    "SY" => array("name" => "República Árabe da Síria", "phone" => 963),
    "TW" => array("name" => "Taiwan, província da China", "phone" => 886),
    "TJ" => array("name" => "Tajiquistão", "phone" => 992),
    "TZ" => array("name" => "Tanzânia, República Unida da", "phone" => 255),
    "TH" => array("name" => "Tailândia", "phone" => 66),
    "TL" => array("name" => "Timor-Leste", "phone" => 670),
    "TG" => array("name" => "Togo", "phone" => 228),
    "TK" => array("name" => "Tokelau", "phone" => 690),
    "TO" => array("name" => "Tonga", "phone" => 676),
    "TT" => array("name" => "Trinidad e Tobago", "phone" => 1868),
    "TN" => array("name" => "Tunísia", "phone" => 216),
    "TR" => array("name" => "Turquia", "phone" => 90),
    "TM" => array("name" => "Turcomenistão", "phone" => 7370),
    "TC" => array("name" => "Ilhas Turcas e Caicos", "phone" => 1649),
    "TV" => array("name" => "Tuvalu", "phone" => 688),
    "UG" => array("name" => "Uganda", "phone" => 256),
    "UA" => array("name" => "Ucrânia", "phone" => 380),
    "AE" => array("name" => "Emirados Árabes Unidos", "phone" => 971),
    "GB" => array("name" => "Reino Unido", "phone" => 44),
    "US" => array("name" => "Estados Unidos", "phone" => 1),
    "UM" => array("name" => "Ilhas Menores Distantes dos Estados Unidos", "phone" => 1),
    "UY" => array("name" => "Uruguai", "phone" => 598),
    "UZ" => array("name" => "Uzbequistão", "phone" => 998),
    "VU" => array("name" => "Vanuatu", "phone" => 678),
    "VE" => array("name" => "Venezuela", "phone" => 58),
    "VN" => array("name" => "Viet Nam", "phone" => 84),
    "VG" => array("name" => "Ilhas Virgens Britânicas", "phone" => 1284),
    "VI" => array("name" => "Ilhas Virgens, EUA", "phone" => 1340),
    "WF" => array("name" => "Wallis e Futuna", "phone" => 681),
    "EH" => array("name" => "Saara Ocidental", "phone" => 212),
    "YE" => array("name" => "Iémen", "phone" => 967),
    "ZM" => array("name" => "Zâmbia", "phone" => 260),
    "ZW" => array("name" => "Zimbábue", "phone" => 263)
);
?>